FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN npm install --production

COPY server-simple.js ./
COPY index.js ./

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 8080

ENV PORT=8080

CMD ["node", "server-simple.js"]
